using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace JsonToObjectConverter.SourceGenerator
{
    /// <summary>
    /// Source generator for creating JSON serialization code.
    /// </summary>
    [Generator]
    public class JsonSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Generate the attributes first (no runtime dependency!)
            context.RegisterPostInitializationOutput(ctx => GenerateAttributes(ctx));

            // Find all classes with [JsonSerializable] attribute
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidateClass(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            // Generate code for each class
            context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(source!, spc));
        }

        private static void GenerateAttributes(IncrementalGeneratorPostInitializationContext context)
        {
            // Generate JsonSerializableAttribute - NO RUNTIME DEPENDENCY!
            const string attributeSource = @"// <auto-generated/>
#nullable enable

namespace JsonToObjectConverter
{
    /// <summary>
    /// Marks a class or struct for JSON serialization code generation.
    /// This attribute is generated by the source generator - no runtime dependency!
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    internal sealed class JsonSerializableAttribute : System.Attribute
    {
    }

    /// <summary>
    /// Specifies a custom JSON property name.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, AllowMultiple = false, Inherited = true)]
    internal sealed class JsonPropertyNameAttribute : System.Attribute
    {
        public string Name { get; }
        public JsonPropertyNameAttribute(string name) => Name = name;
    }

    /// <summary>
    /// Excludes a property from serialization.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, AllowMultiple = false, Inherited = true)]
    internal sealed class JsonIgnoreAttribute : System.Attribute
    {
    }

    /// <summary>
    /// Specifies the discriminator property for polymorphic types.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    internal sealed class JsonTypeDiscriminatorAttribute : System.Attribute
    {
        public string PropertyName { get; }
        public JsonTypeDiscriminatorAttribute(string propertyName) => PropertyName = propertyName;
    }

    /// <summary>
    /// Registers a factory for polymorphic type resolution.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true, Inherited = false)]
    internal sealed class JsonTypeFactoryAttribute : System.Attribute
    {
        public string DiscriminatorValue { get; }
        public System.Type TargetType { get; }
        public JsonTypeFactoryAttribute(string discriminatorValue, System.Type targetType)
        {
            DiscriminatorValue = discriminatorValue;
            TargetType = targetType;
        }
    }
}
";
            context.AddSource("JsonAttributes.g.cs", SourceText.From(attributeSource, Encoding.UTF8));
        }

        private static bool IsCandidateClass(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration &&
                   classDeclaration.AttributeLists.Count > 0;
        }

        private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;

            foreach (var attributeList in classDeclaration.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    var symbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol;
                    if (symbol is not IMethodSymbol attributeSymbol)
                        continue;

                    var attributeClass = attributeSymbol.ContainingType;
                    var fullName = attributeClass.ToDisplayString();

                    if (fullName == "JsonToObjectConverter.JsonSerializableAttribute")
                    {
                        return classDeclaration;
                    }
                }
            }

            return null;
        }

        private static void Execute(ClassDeclarationSyntax classDeclaration, SourceProductionContext context)
        {
            var className = classDeclaration.Identifier.Text;
            var namespaceName = GetNamespace(classDeclaration);

            // Get properties
            var properties = classDeclaration.Members
                .OfType<PropertyDeclarationSyntax>()
                .Where(p => p.Modifiers.Any(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PublicKeyword))
                .ToList();

            var source = GenerateDeserializerCode(namespaceName, className, properties);

            context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
        }

        private static string GetNamespace(ClassDeclarationSyntax classDeclaration)
        {
            var namespaceDeclaration = classDeclaration.Ancestors()
                .OfType<NamespaceDeclarationSyntax>()
                .FirstOrDefault();

            if (namespaceDeclaration != null)
            {
                return namespaceDeclaration.Name.ToString();
            }

            var fileScopedNamespace = classDeclaration.Ancestors()
                .OfType<FileScopedNamespaceDeclarationSyntax>()
                .FirstOrDefault();

            return fileScopedNamespace?.Name.ToString() ?? string.Empty;
        }

        private static string GenerateDeserializerCode(string namespaceName, string className, List<PropertyDeclarationSyntax> properties)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using JsonToObjectConverter.Runtime;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    partial class {className}");
            sb.AppendLine("    {");

            // Generate Deserialize method
            sb.AppendLine($"        public static {className} Deserialize(string json)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var reader = new JsonReader(json);");
            sb.AppendLine($"            var obj = new {className}();");
            sb.AppendLine();
            sb.AppendLine("            reader.ReadObjectStart();");
            sb.AppendLine();
            sb.AppendLine("            while (reader.Read())");
            sb.AppendLine("            {");
            sb.AppendLine("                if (reader.IsObjectEnd()) break;");
            sb.AppendLine();
            sb.AppendLine("                var propertyName = reader.GetString();");
            sb.AppendLine("                reader.ReadColon();");
            sb.AppendLine("                reader.Read();");
            sb.AppendLine();
            sb.AppendLine("                switch (propertyName)");
            sb.AppendLine("                {");

            foreach (var property in properties)
            {
                var propertyName = property.Identifier.Text;
                var propertyType = property.Type.ToString();

                sb.AppendLine($"                    case \"{propertyName}\":");
                sb.AppendLine($"                    case \"{propertyName.ToLowerInvariant()}\":"); // Case-insensitive

                // Generate deserialization code based on type
                if (propertyType == "string")
                {
                    sb.AppendLine($"                        obj.{propertyName} = reader.GetString();");
                }
                else if (propertyType == "int")
                {
                    sb.AppendLine($"                        obj.{propertyName} = reader.GetInt32();");
                }
                else if (propertyType == "long")
                {
                    sb.AppendLine($"                        obj.{propertyName} = reader.GetInt64();");
                }
                else if (propertyType == "double")
                {
                    sb.AppendLine($"                        obj.{propertyName} = reader.GetDouble();");
                }
                else if (propertyType == "decimal")
                {
                    sb.AppendLine($"                        obj.{propertyName} = reader.GetDecimal();");
                }
                else if (propertyType == "bool")
                {
                    sb.AppendLine($"                        obj.{propertyName} = reader.GetBoolean();");
                }
                else
                {
                    // For complex types, assume they also have a Deserialize method
                    sb.AppendLine($"                        // TODO: Deserialize {propertyType}");
                    sb.AppendLine("                        reader.Skip();");
                }

                sb.AppendLine("                        break;");
            }

            sb.AppendLine("                    default:");
            sb.AppendLine("                        reader.Skip();");
            sb.AppendLine("                        break;");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                // Try to read comma");
            sb.AppendLine("                if (reader.Read() && reader.TokenType != JsonTokenType.ObjectEnd)");
            sb.AppendLine("                {");
            sb.AppendLine("                    // Continue to next property");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return obj;");
            sb.AppendLine("        }");

            // Generate Serialize method (simplified)
            sb.AppendLine();
            sb.AppendLine("        public string Serialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            var sb = new System.Text.StringBuilder();");
            sb.AppendLine("            sb.Append('{');");

            for (int i = 0; i < properties.Count; i++)
            {
                var property = properties[i];
                var propertyName = property.Identifier.Text;
                var propertyType = property.Type.ToString();

                if (i > 0)
                {
                    sb.AppendLine("            sb.Append(',');");
                }

                sb.AppendLine($"            sb.Append(\"\\\"{propertyName}\\\":\");");

                if (propertyType == "string")
                {
                    sb.AppendLine($"            sb.Append('\\\"');");
                    sb.AppendLine($"            sb.Append(this.{propertyName});");
                    sb.AppendLine($"            sb.Append('\\\"');");
                }
                else if (propertyType == "int" || propertyType == "long" || propertyType == "double" || propertyType == "decimal")
                {
                    sb.AppendLine($"            sb.Append(this.{propertyName});");
                }
                else if (propertyType == "bool")
                {
                    sb.AppendLine($"            sb.Append(this.{propertyName} ? \"true\" : \"false\");");
                }
                else
                {
                    sb.AppendLine($"            // TODO: Serialize {propertyType}");
                }
            }

            sb.AppendLine("            sb.Append('}');");
            sb.AppendLine("            return sb.ToString();");
            sb.AppendLine("        }");

            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }
    }
}
